services:
  postgres:
    image: postgres:17.2
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jod
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.1.2-management
    container_name: rabbitmq-ui
    ports:
      - "5672:5672"
      - "15672:15672" # rabbitmq management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9002:9000" # minio server
      - "9001:9001" # minio console
    volumes:
      - ../data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    restart: unless-stopped

  mongodb:
    image: mongo:8.0-noble
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ../data/mongodb:/data/db
    restart: unless-stopped
