# Receivers define how the collector receives telemetry data
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

# Processors modify or batch data before exporting
processors:
  batch: # Batches data for efficiency
    send_batch_size: 10000
    send_batch_max_size: 11000

# Exporters send processed data to a destination
exporters:
  otlp:
    endpoint: host.docker.internal:4317
    insecure: true
  otlp/http:
    endpoint: host.docker.internal:4318
    insecure: true

# Extensions add optional features to the collector
extensions:
  health_check:
    endpoint: 0.0.0.0:13133
  pprof:
    endpoint: 0.0.0.0:1777

# Service configures the main collector service
service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
