services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    hostname: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/master:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-net

  redis-replica-1:
    image: redis:latest
    container_name: redis-replica-1
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis/replica-1:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --replicaof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - redis-net

  redis-replica-2:
    image: redis:latest
    container_name: redis-replica-2
    ports:
      - "6381:6379"
    volumes:
      - ./data/redis/replica-2:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --replicaof redis-master 6379
    depends_on:
      - redis-master
    networks:
      - redis-net

  redis-sentinel:
    image: redis:latest
    container_name: redis-sentinel
    ports:
      - "26379:26379"
    volumes:
      - ./data/redis/sentinel:/data
      - ./sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
